![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [16]:
import numpy as np

my_array = np.arange(10)
print(my_array)

print(my_array[::-2])

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [18]:
print(my_array[8:6:-1])
print(my_array[-2:-4:-1])

[8 7]
[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [22]:
print(my_array[0:3][::-1])
print(my_array[2::-1])
print(np.flip(my_array[0:3]))
print(my_array[-8::-1])

[2 1 0]
[2 1 0]
[2 1 0]
[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [23]:
my_matrix = np.arange(1, 21).reshape(4,5)
my_matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [24]:
my_matrix[::-1, ::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [26]:
my_matrix[:2, :2]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [31]:
my_matrix[::2, ::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [33]:
my_matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [35]:
my_matrix[:-1:, ::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [36]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
mask = np.array([True, False, False, True, False])
x[mask]

array(['Loro', 'Loro'], dtype='<U5')

In [41]:
mask = (x == "Loro")
mask
x[mask]
x[x == "Loro"]

array(['Loro', 'Loro'], dtype='<U5')

In [40]:
mask_where = np.where(x == "Loro")
x[mask_where]

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [43]:
x = np.arange(20).reshape((2,5,2))
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [46]:
x = np.zeros(10)
print(x)

print(x.itemsize)
print(x.nbytes)

x[3] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
8
80
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [47]:
x = np.arange(10, 50)
print(x[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [48]:
vector = np.array([1,2,0,0,4,0])
np.where(vector != 0)

(array([0, 1, 4], dtype=int64),)

In [49]:
np.nonzero(vector)

(array([0, 1, 4], dtype=int64),)

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [59]:
x = np.random.randint(1, 100, size = (10,10))
print(x)

print(x.min())
print(np.max(x))

[[89 25 53 38 90 37 95 11  5 23]
 [50 17 34 73 28 52 44 77 22 62]
 [20 32 73 47 83 16 57 47  8 82]
 [83 60 73 81 39 72 26 15 29 58]
 [30 98 46 81 39 36  1 69 90 16]
 [78 61 10 57 58 28 56 84 41 55]
 [31 70 53 39 95 70 88  4 35  7]
 [39 61 85 81 86 63 69 61 76 24]
 [18 70 30 14 75 98 11 42  8 80]
 [94 99 61 23 21 42 47 23 42 50]]
1
99


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [60]:
x = np.random.random(30)
x.mean()

0.5382639416530174

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [70]:
matrix = np.ones((10,5), np.int8)
matrix[1:-1, 1:-1] = 0
print(matrix)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [74]:
x = np.zeros((8,8), np.int8)
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [82]:
x = np.tile(np.array([[0,1], [1,0]]), (4,4))
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [84]:
x = np.random.randint(1, 20, (5,5))

x = (x - np.mean(x))/np.std(x)
print(x)

[[-0.14948986 -0.68338221  0.56236661  0.20643838  0.02847426]
 [ 0.02847426 -0.5054181  -1.21727457  0.02847426  0.74033073]
 [ 0.20643838 -1.39523869  1.27422309  0.91829485 -1.5732028 ]
 [ 1.4521872  -0.14948986  1.09625897  0.91829485  1.27422309]
 [-1.5732028  -0.32745398  1.63015132 -1.39523869 -1.39523869]]


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [88]:
x = np.arange(11)
print(x)

y = x.copy()
y[(y > 3) & (y <= 8)] = -1
print(y)
# np.where(mask, -1, y)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -1 -1 -1 -1 -1  9 10]


In [ ]:
y = x.copy()
y[(y > 3) & (y <= 8)] *= -1
y[(y > 3) & (y <= 8)] = y[(y > 3) & (y <= 8)] * (-1)

## Ejercicio 21 (OPCIONAL SI VAN A HACER HUNDIR LA FLOTA)
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [6]:
import numpy as np
tablero = np.full(fill_value = ' ', shape = (10, 10))


# Barco 1
tablero[0:2, 1] = 'O'

# Barco 2
tablero[1, 3:7] = 'O'

# Disparo
tablero[0, 1] = 'X'

# Agua
tablero[0, 0] = '-'

print(tablero)

[['-' 'X' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [14]:

import random
import numpy as np
tablero = np.full(fill_value = ' ', shape = (10, 10))
eslora = 4

while True:
    orient = random.choice(['N', 'S', 'E', 'O'])
    current_pos = np.random.randint(10, size=2)
    
    fila = current_pos[0]
    col = current_pos[1]
    
    coors_posiN = tablero[fila:fila - eslora:-1, col]
    coors_posiE = tablero[fila, col: col + eslora]
    coors_posiS = tablero[fila:fila + eslora, col]
    coors_posiO = tablero[fila, col:col-eslora:-1]
    
    if (orient == 'N') and (len(coors_posiN) == eslora) and ('O' not in coors_posiN):
        tablero[fila:fila - eslora:-1, col] = 'O'
        break
    
    elif (orient == 'E') and (len(coors_posiE) == eslora) and ('O' not in coors_posiE):
        tablero[fila, col: col + eslora] = 'O'
        break
        
    elif (orient == 'S') and (len(coors_posiS) == eslora) and ('O' not in coors_posiS):
        tablero[fila:fila + eslora, col] = 'O'
        break
    
    elif (orient == 'O') and (len(coors_posiO) == eslora) and ('O' not in coors_posiO):
        tablero[fila, col:col-eslora:-1] = 'O'
        break
        


O
[6 7]


In [ ]:
while True:
    imput
    
    if impacto:
        resto vidas
        le toca de nuevo
    else:
        le toca maquina
        if impacto:
            resto vidas