1. 

En el archivo "logistic_regression_digits" hemos visto un ejemplo multiclase. Elimina todas las imágenes y etiqueta (label) cuyo valor del label no sea 1 o 9. Es decir, elimina todos los dígitos y quédate solo con los dígitos 1 y 9.

Ahora, realiza un entrenamiento con logistic regression con los nuevos datos:

- ¿Se mejora la precisión del algoritmo con dos clases? ¿por qué?

LogisticRegression() es una clase que tiene varios parámetros de entrada. Investiga (toca, modifica, prueba) las variables y comenta si hay alguna de ellas que, modificándola, mejore el porcentaje de acierto del problema.

https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

from sklearn.datasets import load_digits
digits = load_digits() 


import warnings
warnings.filterwarnings('ignore')

In [4]:
digits.data = digits.data[(digits.target == 1) | (digits.target == 9)]
digits.target = digits.target[(digits.target == 1) | (digits.target == 9)]

In [5]:
len(digits.data)

362

In [6]:
X_train, X_test, y_train, y_test = train_test_split(digits.data,
                                                    digits.target,
                                                    test_size=0.2,
                                                    random_state=42)

In [9]:
model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_pred

array([9, 9, 1, 9, 9, 9, 9, 1, 9, 9, 9, 1, 9, 1, 9, 9, 1, 1, 1, 9, 1, 1,
       9, 9, 1, 1, 1, 1, 1, 1, 9, 9, 1, 1, 9, 1, 9, 1, 9, 9, 9, 1, 1, 9,
       9, 1, 1, 9, 9, 1, 1, 9, 9, 1, 1, 1, 1, 9, 1, 1, 9, 9, 9, 1, 1, 1,
       1, 9, 1, 9, 1, 9, 1])

In [10]:
y_test

array([9, 9, 1, 9, 9, 9, 9, 1, 9, 9, 9, 1, 9, 1, 9, 9, 1, 1, 1, 9, 1, 1,
       9, 9, 1, 1, 1, 1, 1, 1, 9, 9, 1, 1, 9, 1, 9, 1, 9, 9, 9, 1, 1, 9,
       9, 1, 1, 9, 9, 1, 1, 9, 9, 1, 1, 9, 1, 9, 1, 1, 9, 9, 9, 1, 1, 1,
       1, 9, 1, 9, 1, 9, 1])

In [12]:
conf_matrix = confusion_matrix(y_test, y_pred)
conf_matrix

array([[37,  0],
       [ 1, 35]], dtype=int64)

In [13]:
model.score(X_train, y_train)

1.0

In [14]:
model.score(X_test, y_test)

0.9863013698630136